baseURL: "https://hiwangzi.com/"
title: WANG!
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Hi, there."
  author: Zi WANG
  comments: true
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: false
  assets:
    favicon: '/images/favicon.ico'

  homeInfoParams:
    Title: "Hi, there ✨"
    Content: "[欢迎你 地球人](/about)"

  socialIcons:
    - name: github
      url: "https://github.com/zill057"
    - name: stackoverflow
      url: "https://stackexchange.com/users/14383694/zill057?tab=activity"
    - name: twitter
      url: "https://twitter.com/zill057"
    - name: rss
      url: "/index.xml"
  
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Archives
      url: /archives
      weight: 5
    - name: Tags
      url: /tags
      weight: 10
    - name: Search
      url: /search
      weight: 15
